/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OauthSuccessRouteImport } from './routes/oauth-success'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as Admin_panelRouteRouteImport } from './routes/admin_panel/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as Admin_panelIndexRouteImport } from './routes/admin_panel/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as Admin_panelUsersRouteImport } from './routes/admin_panel/users'
import { Route as Admin_panelTrashRouteImport } from './routes/admin_panel/trash'
import { Route as Admin_panelTransactionsRouteImport } from './routes/admin_panel/transactions'
import { Route as Admin_panelReport_historyRouteImport } from './routes/admin_panel/report_history'
import { Route as Admin_panelProfileRouteImport } from './routes/admin_panel/profile'
import { Route as Admin_panelPremiumRouteImport } from './routes/admin_panel/premium'
import { Route as Admin_panelFilesRouteImport } from './routes/admin_panel/files'
import { Route as Admin_panelApprovalsRouteImport } from './routes/admin_panel/approvals'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSharedRouteImport } from './routes/_authenticated/shared'
import { Route as AuthenticatedReportedRouteImport } from './routes/_authenticated/reported'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedFoldersRouteImport } from './routes/_authenticated/folders'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCloudRouteImport } from './routes/_authenticated/cloud'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSubjectsIdRouteImport } from './routes/_authenticated/subjects.$id'
import { Route as AuthenticatedSharedShareIdRouteImport } from './routes/_authenticated/shared.$shareId'
import { Route as AuthenticatedPaymentSuccessRouteImport } from './routes/_authenticated/payment.success'
import { Route as AuthenticatedPaymentCancelRouteImport } from './routes/_authenticated/payment.cancel'
import { Route as AuthenticatedFoldersIdRouteImport } from './routes/_authenticated/folders.$id'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'

const OauthSuccessRoute = OauthSuccessRouteImport.update({
  id: '/oauth-success',
  path: '/oauth-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin_panelRouteRoute = Admin_panelRouteRouteImport.update({
  id: '/admin_panel',
  path: '/admin_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const Admin_panelIndexRoute = Admin_panelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Admin_panelRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const Admin_panelUsersRoute = Admin_panelUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => Admin_panelRouteRoute,
} as any)
const Admin_panelTrashRoute = Admin_panelTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => Admin_panelRouteRoute,
} as any)
const Admin_panelTransactionsRoute = Admin_panelTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => Admin_panelRouteRoute,
} as any)
const Admin_panelReport_historyRoute =
  Admin_panelReport_historyRouteImport.update({
    id: '/report_history',
    path: '/report_history',
    getParentRoute: () => Admin_panelRouteRoute,
  } as any)
const Admin_panelProfileRoute = Admin_panelProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => Admin_panelRouteRoute,
} as any)
const Admin_panelPremiumRoute = Admin_panelPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => Admin_panelRouteRoute,
} as any)
const Admin_panelFilesRoute = Admin_panelFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => Admin_panelRouteRoute,
} as any)
const Admin_panelApprovalsRoute = Admin_panelApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => Admin_panelRouteRoute,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSharedRoute = AuthenticatedSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportedRoute = AuthenticatedReportedRouteImport.update({
  id: '/reported',
  path: '/reported',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoldersRoute = AuthenticatedFoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCloudRoute = AuthenticatedCloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubjectsIdRoute = AuthenticatedSubjectsIdRouteImport.update({
  id: '/subjects/$id',
  path: '/subjects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSharedShareIdRoute =
  AuthenticatedSharedShareIdRouteImport.update({
    id: '/$shareId',
    path: '/$shareId',
    getParentRoute: () => AuthenticatedSharedRoute,
  } as any)
const AuthenticatedPaymentSuccessRoute =
  AuthenticatedPaymentSuccessRouteImport.update({
    id: '/payment/success',
    path: '/payment/success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentCancelRoute =
  AuthenticatedPaymentCancelRouteImport.update({
    id: '/payment/cancel',
    path: '/payment/cancel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFoldersIdRoute = AuthenticatedFoldersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedFoldersRoute,
} as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin_panel': typeof Admin_panelRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/oauth-success': typeof OauthSuccessRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/cloud': typeof AuthenticatedCloudRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/folders': typeof AuthenticatedFoldersRouteWithChildren
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reported': typeof AuthenticatedReportedRoute
  '/shared': typeof AuthenticatedSharedRouteWithChildren
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/admin_panel/approvals': typeof Admin_panelApprovalsRoute
  '/admin_panel/files': typeof Admin_panelFilesRoute
  '/admin_panel/premium': typeof Admin_panelPremiumRoute
  '/admin_panel/profile': typeof Admin_panelProfileRoute
  '/admin_panel/report_history': typeof Admin_panelReport_historyRoute
  '/admin_panel/transactions': typeof Admin_panelTransactionsRoute
  '/admin_panel/trash': typeof Admin_panelTrashRoute
  '/admin_panel/users': typeof Admin_panelUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin_panel/': typeof Admin_panelIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/folders/$id': typeof AuthenticatedFoldersIdRoute
  '/payment/cancel': typeof AuthenticatedPaymentCancelRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/shared/$shareId': typeof AuthenticatedSharedShareIdRoute
  '/subjects/$id': typeof AuthenticatedSubjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oauth-success': typeof OauthSuccessRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai': typeof AuthenticatedAiRoute
  '/cloud': typeof AuthenticatedCloudRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/folders': typeof AuthenticatedFoldersRouteWithChildren
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reported': typeof AuthenticatedReportedRoute
  '/shared': typeof AuthenticatedSharedRouteWithChildren
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/admin_panel/approvals': typeof Admin_panelApprovalsRoute
  '/admin_panel/files': typeof Admin_panelFilesRoute
  '/admin_panel/premium': typeof Admin_panelPremiumRoute
  '/admin_panel/profile': typeof Admin_panelProfileRoute
  '/admin_panel/report_history': typeof Admin_panelReport_historyRoute
  '/admin_panel/transactions': typeof Admin_panelTransactionsRoute
  '/admin_panel/trash': typeof Admin_panelTrashRoute
  '/admin_panel/users': typeof Admin_panelUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin_panel': typeof Admin_panelIndexRoute
  '/auth': typeof AuthIndexRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/folders/$id': typeof AuthenticatedFoldersIdRoute
  '/payment/cancel': typeof AuthenticatedPaymentCancelRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/shared/$shareId': typeof AuthenticatedSharedShareIdRoute
  '/subjects/$id': typeof AuthenticatedSubjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin_panel': typeof Admin_panelRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/oauth-success': typeof OauthSuccessRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/cloud': typeof AuthenticatedCloudRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/_authenticated/folders': typeof AuthenticatedFoldersRouteWithChildren
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reported': typeof AuthenticatedReportedRoute
  '/_authenticated/shared': typeof AuthenticatedSharedRouteWithChildren
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
  '/admin_panel/approvals': typeof Admin_panelApprovalsRoute
  '/admin_panel/files': typeof Admin_panelFilesRoute
  '/admin_panel/premium': typeof Admin_panelPremiumRoute
  '/admin_panel/profile': typeof Admin_panelProfileRoute
  '/admin_panel/report_history': typeof Admin_panelReport_historyRoute
  '/admin_panel/transactions': typeof Admin_panelTransactionsRoute
  '/admin_panel/trash': typeof Admin_panelTrashRoute
  '/admin_panel/users': typeof Admin_panelUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin_panel/': typeof Admin_panelIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/folders/$id': typeof AuthenticatedFoldersIdRoute
  '/_authenticated/payment/cancel': typeof AuthenticatedPaymentCancelRoute
  '/_authenticated/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/_authenticated/shared/$shareId': typeof AuthenticatedSharedShareIdRoute
  '/_authenticated/subjects/$id': typeof AuthenticatedSubjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin_panel'
    | '/auth'
    | '/oauth-success'
    | '/admin'
    | '/ai'
    | '/cloud'
    | '/dashboard'
    | '/documents'
    | '/folders'
    | '/premium'
    | '/profile'
    | '/reported'
    | '/shared'
    | '/transactions'
    | '/trash'
    | '/admin_panel/approvals'
    | '/admin_panel/files'
    | '/admin_panel/premium'
    | '/admin_panel/profile'
    | '/admin_panel/report_history'
    | '/admin_panel/transactions'
    | '/admin_panel/trash'
    | '/admin_panel/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/admin_panel/'
    | '/auth/'
    | '/documents/$id'
    | '/folders/$id'
    | '/payment/cancel'
    | '/payment/success'
    | '/shared/$shareId'
    | '/subjects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/oauth-success'
    | '/admin'
    | '/ai'
    | '/cloud'
    | '/dashboard'
    | '/documents'
    | '/folders'
    | '/premium'
    | '/profile'
    | '/reported'
    | '/shared'
    | '/transactions'
    | '/trash'
    | '/admin_panel/approvals'
    | '/admin_panel/files'
    | '/admin_panel/premium'
    | '/admin_panel/profile'
    | '/admin_panel/report_history'
    | '/admin_panel/transactions'
    | '/admin_panel/trash'
    | '/admin_panel/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/admin_panel'
    | '/auth'
    | '/documents/$id'
    | '/folders/$id'
    | '/payment/cancel'
    | '/payment/success'
    | '/shared/$shareId'
    | '/subjects/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin_panel'
    | '/auth'
    | '/oauth-success'
    | '/_authenticated/admin'
    | '/_authenticated/ai'
    | '/_authenticated/cloud'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/folders'
    | '/_authenticated/premium'
    | '/_authenticated/profile'
    | '/_authenticated/reported'
    | '/_authenticated/shared'
    | '/_authenticated/transactions'
    | '/_authenticated/trash'
    | '/admin_panel/approvals'
    | '/admin_panel/files'
    | '/admin_panel/premium'
    | '/admin_panel/profile'
    | '/admin_panel/report_history'
    | '/admin_panel/transactions'
    | '/admin_panel/trash'
    | '/admin_panel/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/admin_panel/'
    | '/auth/'
    | '/_authenticated/documents/$id'
    | '/_authenticated/folders/$id'
    | '/_authenticated/payment/cancel'
    | '/_authenticated/payment/success'
    | '/_authenticated/shared/$shareId'
    | '/_authenticated/subjects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  Admin_panelRouteRoute: typeof Admin_panelRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OauthSuccessRoute: typeof OauthSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oauth-success': {
      id: '/oauth-success'
      path: '/oauth-success'
      fullPath: '/oauth-success'
      preLoaderRoute: typeof OauthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_panel': {
      id: '/admin_panel'
      path: '/admin_panel'
      fullPath: '/admin_panel'
      preLoaderRoute: typeof Admin_panelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin_panel/': {
      id: '/admin_panel/'
      path: '/'
      fullPath: '/admin_panel/'
      preLoaderRoute: typeof Admin_panelIndexRouteImport
      parentRoute: typeof Admin_panelRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin_panel/users': {
      id: '/admin_panel/users'
      path: '/users'
      fullPath: '/admin_panel/users'
      preLoaderRoute: typeof Admin_panelUsersRouteImport
      parentRoute: typeof Admin_panelRouteRoute
    }
    '/admin_panel/trash': {
      id: '/admin_panel/trash'
      path: '/trash'
      fullPath: '/admin_panel/trash'
      preLoaderRoute: typeof Admin_panelTrashRouteImport
      parentRoute: typeof Admin_panelRouteRoute
    }
    '/admin_panel/transactions': {
      id: '/admin_panel/transactions'
      path: '/transactions'
      fullPath: '/admin_panel/transactions'
      preLoaderRoute: typeof Admin_panelTransactionsRouteImport
      parentRoute: typeof Admin_panelRouteRoute
    }
    '/admin_panel/report_history': {
      id: '/admin_panel/report_history'
      path: '/report_history'
      fullPath: '/admin_panel/report_history'
      preLoaderRoute: typeof Admin_panelReport_historyRouteImport
      parentRoute: typeof Admin_panelRouteRoute
    }
    '/admin_panel/profile': {
      id: '/admin_panel/profile'
      path: '/profile'
      fullPath: '/admin_panel/profile'
      preLoaderRoute: typeof Admin_panelProfileRouteImport
      parentRoute: typeof Admin_panelRouteRoute
    }
    '/admin_panel/premium': {
      id: '/admin_panel/premium'
      path: '/premium'
      fullPath: '/admin_panel/premium'
      preLoaderRoute: typeof Admin_panelPremiumRouteImport
      parentRoute: typeof Admin_panelRouteRoute
    }
    '/admin_panel/files': {
      id: '/admin_panel/files'
      path: '/files'
      fullPath: '/admin_panel/files'
      preLoaderRoute: typeof Admin_panelFilesRouteImport
      parentRoute: typeof Admin_panelRouteRoute
    }
    '/admin_panel/approvals': {
      id: '/admin_panel/approvals'
      path: '/approvals'
      fullPath: '/admin_panel/approvals'
      preLoaderRoute: typeof Admin_panelApprovalsRouteImport
      parentRoute: typeof Admin_panelRouteRoute
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shared': {
      id: '/_authenticated/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof AuthenticatedSharedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reported': {
      id: '/_authenticated/reported'
      path: '/reported'
      fullPath: '/reported'
      preLoaderRoute: typeof AuthenticatedReportedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/folders': {
      id: '/_authenticated/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof AuthenticatedFoldersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cloud': {
      id: '/_authenticated/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof AuthenticatedCloudRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/$id': {
      id: '/_authenticated/subjects/$id'
      path: '/subjects/$id'
      fullPath: '/subjects/$id'
      preLoaderRoute: typeof AuthenticatedSubjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shared/$shareId': {
      id: '/_authenticated/shared/$shareId'
      path: '/$shareId'
      fullPath: '/shared/$shareId'
      preLoaderRoute: typeof AuthenticatedSharedShareIdRouteImport
      parentRoute: typeof AuthenticatedSharedRoute
    }
    '/_authenticated/payment/success': {
      id: '/_authenticated/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof AuthenticatedPaymentSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment/cancel': {
      id: '/_authenticated/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof AuthenticatedPaymentCancelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/folders/$id': {
      id: '/_authenticated/folders/$id'
      path: '/$id'
      fullPath: '/folders/$id'
      preLoaderRoute: typeof AuthenticatedFoldersIdRouteImport
      parentRoute: typeof AuthenticatedFoldersRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
  }
}

interface AuthenticatedDocumentsRouteChildren {
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
}

const AuthenticatedDocumentsRouteChildren: AuthenticatedDocumentsRouteChildren =
  {
    AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  }

const AuthenticatedDocumentsRouteWithChildren =
  AuthenticatedDocumentsRoute._addFileChildren(
    AuthenticatedDocumentsRouteChildren,
  )

interface AuthenticatedFoldersRouteChildren {
  AuthenticatedFoldersIdRoute: typeof AuthenticatedFoldersIdRoute
}

const AuthenticatedFoldersRouteChildren: AuthenticatedFoldersRouteChildren = {
  AuthenticatedFoldersIdRoute: AuthenticatedFoldersIdRoute,
}

const AuthenticatedFoldersRouteWithChildren =
  AuthenticatedFoldersRoute._addFileChildren(AuthenticatedFoldersRouteChildren)

interface AuthenticatedSharedRouteChildren {
  AuthenticatedSharedShareIdRoute: typeof AuthenticatedSharedShareIdRoute
}

const AuthenticatedSharedRouteChildren: AuthenticatedSharedRouteChildren = {
  AuthenticatedSharedShareIdRoute: AuthenticatedSharedShareIdRoute,
}

const AuthenticatedSharedRouteWithChildren =
  AuthenticatedSharedRoute._addFileChildren(AuthenticatedSharedRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedCloudRoute: typeof AuthenticatedCloudRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRouteWithChildren
  AuthenticatedFoldersRoute: typeof AuthenticatedFoldersRouteWithChildren
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportedRoute: typeof AuthenticatedReportedRoute
  AuthenticatedSharedRoute: typeof AuthenticatedSharedRouteWithChildren
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
  AuthenticatedPaymentCancelRoute: typeof AuthenticatedPaymentCancelRoute
  AuthenticatedPaymentSuccessRoute: typeof AuthenticatedPaymentSuccessRoute
  AuthenticatedSubjectsIdRoute: typeof AuthenticatedSubjectsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedCloudRoute: AuthenticatedCloudRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRouteWithChildren,
  AuthenticatedFoldersRoute: AuthenticatedFoldersRouteWithChildren,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportedRoute: AuthenticatedReportedRoute,
  AuthenticatedSharedRoute: AuthenticatedSharedRouteWithChildren,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
  AuthenticatedPaymentCancelRoute: AuthenticatedPaymentCancelRoute,
  AuthenticatedPaymentSuccessRoute: AuthenticatedPaymentSuccessRoute,
  AuthenticatedSubjectsIdRoute: AuthenticatedSubjectsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface Admin_panelRouteRouteChildren {
  Admin_panelApprovalsRoute: typeof Admin_panelApprovalsRoute
  Admin_panelFilesRoute: typeof Admin_panelFilesRoute
  Admin_panelPremiumRoute: typeof Admin_panelPremiumRoute
  Admin_panelProfileRoute: typeof Admin_panelProfileRoute
  Admin_panelReport_historyRoute: typeof Admin_panelReport_historyRoute
  Admin_panelTransactionsRoute: typeof Admin_panelTransactionsRoute
  Admin_panelTrashRoute: typeof Admin_panelTrashRoute
  Admin_panelUsersRoute: typeof Admin_panelUsersRoute
  Admin_panelIndexRoute: typeof Admin_panelIndexRoute
}

const Admin_panelRouteRouteChildren: Admin_panelRouteRouteChildren = {
  Admin_panelApprovalsRoute: Admin_panelApprovalsRoute,
  Admin_panelFilesRoute: Admin_panelFilesRoute,
  Admin_panelPremiumRoute: Admin_panelPremiumRoute,
  Admin_panelProfileRoute: Admin_panelProfileRoute,
  Admin_panelReport_historyRoute: Admin_panelReport_historyRoute,
  Admin_panelTransactionsRoute: Admin_panelTransactionsRoute,
  Admin_panelTrashRoute: Admin_panelTrashRoute,
  Admin_panelUsersRoute: Admin_panelUsersRoute,
  Admin_panelIndexRoute: Admin_panelIndexRoute,
}

const Admin_panelRouteRouteWithChildren =
  Admin_panelRouteRoute._addFileChildren(Admin_panelRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  Admin_panelRouteRoute: Admin_panelRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OauthSuccessRoute: OauthSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
